-- AlterTable
ALTER TABLE "Purchase" ADD COLUMN     "exemptAmount" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "iibbPerceptionAmount" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "internalTaxAmount" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "invoicePointOfSale" INTEGER,
ADD COLUMN     "invoiceType" INTEGER,
ADD COLUMN     "ivaPerceptionAmount" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "municipalPerceptionAmount" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "nationalTaxPerceptionAmount" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "nonTaxedAmount" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "providerCuit" TEXT;

-- AlterTable
ALTER TABLE "PurchaseItem" ADD COLUMN     "ivaRate" DOUBLE PRECISION NOT NULL DEFAULT 21;
