services:
  mosquitto:
    build: .
    ports:
      - "1883:1883" # solo para debug local, no exponer en prod
      - "8883:8883"
    volumes:
      - mosquitto-data:/mosquitto/data
      - ./certs:/mosquitto/certs:ro
    environment:
      MQTT_ADMIN_USERNAME: ${MQTT_ADMIN_USERNAME:?}
      MQTT_ADMIN_PASSWORD: ${MQTT_ADMIN_PASSWORD:?}
    restart: unless-stopped

volumes:
  mosquitto-data:
