-- AlterTable
ALTER TABLE "Product" ADD COLUMN     "ivaRate" DOUBLE PRECISION NOT NULL DEFAULT 21;

-- AlterTable
ALTER TABLE "SaleItem" ADD COLUMN     "ivaRate" DOUBLE PRECISION NOT NULL DEFAULT 21;
